[build]
  command = "npm run build"  # Ensure these commands work correctly
  functions = "functions"               # Points to your function directory
  publish = "dist"           # Points to your published static files
